# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpjungle < Formula
  desc "Self-hosted MCP tool registry for enterprise AI agents"
  homepage "https://github.com/mcpjungle/MCPJungle"
  version "0.2.20"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.2.20/mcpjungle_Darwin_x86_64.tar.gz"
      sha256 "19718cae7af0004fab499ca8c412568f3c534ba65a5c808a0f352f0dae455465"

      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.2.20/mcpjungle_Darwin_arm64.tar.gz"
      sha256 "9e3edd04a73f52f708934e390e1b7761e8c62f613da07092a4d8efe5a7fd425c"

      def install
        bin.install "mcpjungle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.2.20/mcpjungle_Linux_x86_64.tar.gz"
      sha256 "b4b922b9842499344d4d0d4e641c2a4eba8fc5a0d3e8f6088702a500f47adee9"
      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.2.20/mcpjungle_Linux_arm64.tar.gz"
      sha256 "8778df6ff5619fb26b5f07c7283b850eacd2fd609e22149de6ac7b0610877dd0"
      def install
        bin.install "mcpjungle"
      end
    end
  end
end
