# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpjungle < Formula
  desc "Self-hosted MCP tool registry for enterprise AI agents"
  homepage "https://github.com/mcpjungle/MCPJungle"
  version "0.1.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/v0.1.14/MCPJungle_Darwin_x86_64.tar.gz"
      sha256 "76f0b601a5c67cf815873e50469f9a7d762d61c48628e7b71e53563aede45de2"

      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/v0.1.14/MCPJungle_Darwin_arm64.tar.gz"
      sha256 "17555cfc1286f362711cc8b73cdf5726913b7ec4e342f387ef2eea8c6dbb35d9"

      def install
        bin.install "mcpjungle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/v0.1.14/MCPJungle_Linux_x86_64.tar.gz"
      sha256 "eee251241fdb82c808a88dd4be07346f61ec8c834980ec5713d5781ae9be3a85"
      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/v0.1.14/MCPJungle_Linux_arm64.tar.gz"
      sha256 "c6b53646e169a263079afe31f4bb264fcff00ed39e87cfdbc60832422f53963e"
      def install
        bin.install "mcpjungle"
      end
    end
  end
end
