# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpjungle < Formula
  desc "Self-hosted MCP tool registry for enterprise AI agents"
  homepage "https://github.com/mcpjungle/MCPJungle"
  version "0.1.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/v0.1.10/MCPJungle_Darwin_x86_64.tar.gz"
      sha256 "7d4d07a92c5493ae3cf4a12458486133a1cee0d4c04cb4cc8ffe743583d4bdfd"

      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/v0.1.10/MCPJungle_Darwin_arm64.tar.gz"
      sha256 "f4f6d6f3a91c22cfc29e20b47d7e1d45079be17582b3c1f1d85f45e1b4fa6308"

      def install
        bin.install "mcpjungle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/v0.1.10/MCPJungle_Linux_x86_64.tar.gz"
      sha256 "39ac4a1f22af4d23989aa8239549ee17432ca1f4ef376ec0cad8a17da6e4c7cc"
      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/v0.1.10/MCPJungle_Linux_arm64.tar.gz"
      sha256 "03ee3d7fece9443da9eb2444fc657f17d556584a129b145a790248095cf38f05"
      def install
        bin.install "mcpjungle"
      end
    end
  end
end
