# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpjungle < Formula
  desc "Self-hosted MCP tool registry for enterprise AI agents"
  homepage "https://github.com/mcpjungle/MCPJungle"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.2.1/MCPJungle_Darwin_x86_64.tar.gz"
      sha256 "7ef0add98f269438ded6ac873d60358a79a0a9326f278f88a9b17664970c044f"

      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.2.1/MCPJungle_Darwin_arm64.tar.gz"
      sha256 "546ed50bbac51037422f5e326395e00c2419081196c5a75f69cd90a6e69e2d33"

      def install
        bin.install "mcpjungle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.2.1/MCPJungle_Linux_x86_64.tar.gz"
      sha256 "2d949361421f78e9fc1ced35ad0e7a133c9f75e7a06beb45226b3c94c8af36ef"
      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.2.1/MCPJungle_Linux_arm64.tar.gz"
      sha256 "6c712be53283432dbf76df3d4ae806d822b96d49b3ed26e2bfabfd958665ca73"
      def install
        bin.install "mcpjungle"
      end
    end
  end
end
