# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpjungle < Formula
  desc "Self-hosted MCP tool registry for enterprise AI agents"
  homepage "https://github.com/mcpjungle/MCPJungle"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.3.2/mcpjungle_Darwin_x86_64.tar.gz"
      sha256 "1b8c6a5572ae8d6da9c2093cf924f0582d30943ffd0063fc8bd4bd5e23f709cf"

      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.3.2/mcpjungle_Darwin_arm64.tar.gz"
      sha256 "56d1721fa34fe9b3bc87b37af88441b9fa00419382ff382861779e5f7d64a162"

      def install
        bin.install "mcpjungle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.3.2/mcpjungle_Linux_x86_64.tar.gz"
      sha256 "766c48b0c082e92f622e46328550a8aa8b8a9fc83da2e648d6f50607edf25861"
      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.3.2/mcpjungle_Linux_arm64.tar.gz"
      sha256 "11ae50193dc3a92f5d741cb7a092543bfcdd8e9cdf3f500f57236ac2f1568a5d"
      def install
        bin.install "mcpjungle"
      end
    end
  end
end
