# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpjungle < Formula
  desc "Self-hosted MCP tool registry for enterprise AI agents"
  homepage "https://github.com/mcpjungle/MCPJungle"
  version "0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.3/mcpjungle_Darwin_x86_64.tar.gz"
      sha256 "c6fc96d6129907b7857ac538541ddd911ccfdc98e6dc20e1d44a914a392c981f"

      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.3/mcpjungle_Darwin_arm64.tar.gz"
      sha256 "3d7d8bdefd8626f5a8171a977530e39819adef82b121e909ee3ee87ee0267ad8"

      def install
        bin.install "mcpjungle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.3/mcpjungle_Linux_x86_64.tar.gz"
      sha256 "bf55d0b587dd744bb0273a0d977802e826818c8fbaa29fdcbe262b60b4a3bdac"
      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcpjungle/MCPJungle/releases/download/0.3/mcpjungle_Linux_arm64.tar.gz"
      sha256 "09cba168d76b3b9b2533deb63fcac714fe7a03e45af095fb80b6486fb8bd8caa"
      def install
        bin.install "mcpjungle"
      end
    end
  end
end
